pipeline {
    agent {
        docker { image 'node:18' } // Pulls Node.js 18 with npm pre-installed
    }

    environment {
        DB_HOST = "${DB_HOST}"
        DB_NAME = "${DB_NAME}"
        DB_USER = "${DB_USER}"
        DB_PASSWORD = credentials('daip-db-password')
    }
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out code from Git repository...'
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/develop']],
                    userRemoteConfigs: [[url: 'https://github.com/paulos-andrade/node-api-daip.git']]
                ])
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                echo "Database Host: ${env.DB_HOST}"
                echo "Database Name: ${env.DB_NAME}"
                echo "Database User: ${env.DB_USER}"

                echo 'Running tests...'
                sh 'npm test'
            }
        }

        stage('Build Application') {
            steps {
                echo 'Building application...'
                sh 'npm run build'
            }
        }
    }
}
