pipeline {
    agent any
    environment {
        DB_HOST = "${DB_HOST}"
        DB_NAME = "${DB_NAME}"
        DB_USER = "${DB_USER}"
        DB_PASSWORD = credentials('daip-db-password')
        DOCKERFILE_PATH = "${DOCKER_PATH}"
        IMAGE_NAME = "${IMAGE_NAME}"
    }
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out code from Git repository...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    docker.image('node:18').inside {
                        echo 'Installing dependencies...'
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image('node:18').inside {
                        echo 'Running tests...'
                        sh 'npm test'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building Docker image...'
                    cleanWs()
                    docker.build("${IMAGE_NAME}", "-f ${DOCKERFILE_PATH} .")
                }
            }
        }
    }
}
